version: '3.5'


services:
  postgres:
    container_name: mesa_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "9999:5432"

volumes:
  postgres-db:
    driver: local
